server.port=8081

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/etour_db
spring.datasource.username=postgres
spring.datasource.password=13032004
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate JPA configurations (Auto creates tables 'users', 'tours', 'bookings')
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Spring Mail dummy properties (simulate SMTP locally)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
